### PR TITLE
Edgecenter removal

### PR DESCRIPTION
**Pull request by MarianaStrix**
EdgeCenter and Gcore are 2 different and unrelated companies that temporarily have a similar API structure, but it will drastically change in the near future. If Edgecenter decide to support octodns integration I believe they will provide PR with their module implementation. Now we can not declare compatibility and commit to support their API

@mjekson @jimaek Let's discuss here what we need to do to separate our code.

### CODE REVIEW

**Comment by mjekson** [comment]
> @mjekson @jimaek Let's discuss here what we need to do to separate our code.

Hi, so I think, we need to fork this module and then to edit it to EdgeCentre api.

**Comment by ross** [comment]
> Hi, so I think, we need to fork this module and then to edit it to EdgeCentre api.

https://github.com/octodns/terraformed/pull/14 created the module repo.

I then pushed the contents of gcore there as-is. 

@mjekson if you want to fork that repo and get a PR going to make the updates/changes across that repo I'll :eye:, ✅, and we can ship it and get a module up on pypi. Once that's happened this can ship.

**Comment by mjekson** [comment]
> if you want to fork that repo and get a PR going to make the updates/changes across that repo I'll 👁️, ✅, and we can ship it and get a module up on pypi. Once that's happened this can ship.

@ross thank you, I see "octodns/octodns-edgecenter" so I can make a new PR

**Comment by ross** [comment]
EdgeCenterProvider has been forked/extracted: https://github.com/octodns/octodns-edgecenter/pull/1 and released https://pypi.org/project/octodns-edgecenter/0.0.1/

**Pull request merged**
