### PR TITLE
Fixed validation unsupported provinces, EdgeCenterProvider removed

### PR DESCRIPTION
**Pull request by MarianaStrix**
EdgeCenter and Gcore are 2 different and unrelated companies that temporarily have a similar API structure, but it will drastically change in the near future. If Edgecenter decide to support octodns integration I believe they will provide PR with their module implementation. Now we can not declare compatibility and commit to support their API

### CODE REVIEW

**Comment by ross** [comment]
> EdgeCenter and Gcore are 2 different and unrelated companies that temporarily have a similar API structure, but it will drastically change in the near future. If Edgecenter decide to support octodns integration I believe they will provide PR with their module implementation. Now we can not declare compatibility and commit to support their API

We'd want to deprecate this with error messages pointing to the location of the new & different provider for a while before completely removing it. That also means we'll want to wait until the differences have happened and a new provider exists. 

Wouldn't expect/require you all to support a different company past the point at which the API are no longer compatible. 

More generally this PR is probably best broken up into separate bits with a 1 PR 1 change approach, in this case that'd mean breaking out the validation changes.  Guess the gcorelabs -> gcore changes could be their own PR as well.

**Comment by jimaek** [comment]
Is it really necessary to support edgecenter? They were added only recently https://github.com/octodns/octodns-gcore/commit/af03dda5140250bff28af0963ad6e356989bf096 and it looks like it was done on an mistaken assumption that it's the same company. 

It's like adding Google DNS support to NS1 module :)

**Comment by ross** [comment]
> Is it really necessary to support edgecenter? They were added only recently [af03dda](https://github.com/octodns/octodns-gcore/commit/af03dda5140250bff28af0963ad6e356989bf096) and it looks like it was done on an mistaken assumption that it's the same company.

I thought the discussion was in an issue, but it appears I mis-remembered and it was actually an email from @mjekson, who was mentioned on the PR https://github.com/octodns/octodns-gcore/pull/14. 

I wasn't under the impression that they were the same company, just that they used the same APIs and were interchangeable as far as the provider was concerned. He originally mentioned a new provider and I was the one that guided things towards using the same provider, with a refactor rather than having 2 effectively identical code bases.

> It's like adding Google DNS support to NS1 module :)

If they had the same API I'd be perfectly happy to combine them and avoid identical/duplicated code and maintenance overhead. octoDNS isn't a commercial endeavor and isn't affiliated with any of the companies that it has providers for. It optimizes for the least code/effort in order to focus the donated time of myself and others on providing the most value to the most people.

**Comment by mjekson** [comment]
hi, i totally agree with @ross . Edgecenter requires support for the OctoDNS module. I wanted to ask @ross to make a separate module for Edgecenter, but decided not to duplicate the code, but just make an additional class with the Edgecenter API.

**Comment by mjekson** [comment]
@MarianaStrix don't remove please)))

**Comment by mjekson** [comment]
@ross please change https://api.edgecenter.ru/id TO => https://api.edgecenter.ru/iam

**Comment by jimaek** [comment]
This module is named "gcore". Edgecenter has no place here, so the only question is what is the correct procedure to remove it.

@MarianaStrix please do as Ross said and break the PR into 3. 

1. PR with G-Core->Gcore rename
2. Fixed validation unsupported provinces
3. Edgecenter removal, we can continue the discussion about the correct approach there.

**Comment by mjekson** [comment]
@jimaek OK. Let's make a separate module for Edgecenter API. We really need it, because our clients are heavily dependent on OctoDNS

**Comment by mjekson** [comment]
@ross If you can fork this module to Edgecenter, so I can help you to review it

**Comment by ross** [comment]
> @ross If you can fork this module to Edgecenter, so I can help you to review it

I'll probably be a day or so before I get to sit down and do the terraform bits to create a new repo and copy things over. Will do so when I get a chance.

**Comment by mjekson** [comment]
@ross You can invite me as a new member with role as developer to "octodns-ec" or invite to another group. I'll help you to support this module if I can create a new branch for your project.

**Comment by MarianaStrix** [comment]
Ok, I'm going to create 3 new PR. Thanks!

**Comment by MarianaStrix** [comment]
> @ross please change https://api.edgecenter.ru/id TO => https://api.edgecenter.ru/iam

I fixed it in my PR

**Pull request closed without merging**
